#include <stdio.h>
#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"
#include "btstack.h"
#include "remote_service.h" // Generated by CMake from .gatt

static btstack_packet_callback_registration_t hci_event_callback_registration;
static uint16_t led_value = 0;

// Functions to execute remotely
void execute_remote_command(uint8_t command) {
    if (command == 0x01) {
        printf("Command Received: LED ON\n");
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);
    } else if (command == 0x00) {
        printf("Command Received: LED OFF\n");
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 0);
    }
}

// GATT Write Callback
static uint16_t att_write_callback(hci_con_handle_t con_handle, uint16_t att_handle, uint16_t transaction_mode, uint16_t offset, uint8_t *buffer, uint16_t buffer_size) {
    // Check if the write is to our custom characteristic
    if (att_handle == ATT_CHARACTERISTIC_0000FF02_0000_1000_8000_00805F9B34FB_01_VALUE_HANDLE) {
        execute_remote_command(buffer[0]);
    }
    return 0;
}

static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    if (packet_type != HCI_EVENT_PACKET) return;
    if (hci_event_packet_get_type(packet) == BTSTACK_EVENT_STATE) {
        if (btstack_event_state_get_state(packet) == HCI_STATE_WORKING) {
            printf("BTstack up and running!\n");
        }
    }
}

int main() {
    stdio_init_all();

    // Initialize CYW43 (Wifi/BT chip)
    if (cyw43_arch_init()) {
        printf("Failed to init cyw43\n");
        return -1;
    }

    l2cap_init();
    sm_init();
    att_server_init(profile_data, NULL, att_write_callback);

    // Setup Advertisement
    uint16_t adv_int_min = 0x0030;
    uint16_t adv_int_max = 0x0030;
    uint8_t adv_type = 0;
    bd_addr_t null_addr;
    memset(null_addr, 0, 6);
    gap_advertisements_set_params(adv_int_min, adv_int_max, adv_type, 0, null_addr, 0x07, 0x00);
    
    // Set Device Name in Adv Data
    uint8_t adv_data[] = { 0x02, 0x01, 0x06, 0x0c, 0x09, 'P', 'i', 'c', 'o', '2', 'W', '_', 'R', 'e', 'm', 'o' };
    gap_advertisements_set_data(sizeof(adv_data), adv_data);
    gap_advertisements_enable(1);

    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    hci_power_control(HCI_POWER_ON);

    while (true) {
        // BTstack runs in the background via async events
        __wfe();
    }
}