#ifndef _BTSTACK_CONFIG_H
#define _BTSTACK_CONFIG_H

#define HAVE_EMBEDDED_TIME_MS
#define HAVE_BTSTACK_STDIN
#define HAVE_HAL_AUDIO_SINK_DMA

#define MAX_NR_GATT_CLIENT_VALUETYPES 1
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_SERVICES  2
#define MAX_NR_L2CAP_CHANNELS  2
#define MAX_NR_GATT_SERVICES   3
#define MAX_NR_GATT_CLIENTS    1
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_SERVICE_RECORD_ITEMS 10

#endif